### ISSUE TITLE
Not receiving any notification and app stops running in the background at the triggering time (Android).

### ISSUE THREAD

**Issue by ShridharCodewave** [wumke/react-native-local-notifications#17]
RNLocalNotifications.createNotification(
      1,
      "Some text",
      "2018-10-12 12:26",
      "default"
    );

If I run the app in the background it stops at exactly 12:26 ,
If the app is open nothing happens

**Comment by wumke** [comment]
That is a strange issue, I also use it for setting notifications in background when silent push notifications are recieved (in iOS and Android). 

On which platform version do you have this issues? 
Which android build, target,... versions do you use?
Any kind of log at time of error?
Any kind of logs at time of 'nothing happens' case?

**Comment by wumke** [comment]
Ah, wait a minute, since higher android versions there is a need to set the notification channel! (wether is needed depends on which os version you target...)
Can you try by adding the following to AlarmReceiver.java:
```
import android.app.NotificationChannel;
import android.app.NotificationManager;
...
               NotificationManager notificationManager = (NotificationManager) context.getSystemService(context.NOTIFICATION_SERVICE);

                if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.O) {
                    mBuilder.setChannelId("be.lucine_os.bethanienhuis");
                }
                if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.O) {
                    NotificationChannel channel = new NotificationChannel(
                            "com.myawesomeapp.id",
                            "MyAwesomeApp",
                            NotificationManager.IMPORTANCE_HIGH
                    );
                    if (notificationManager != null) {
                        notificationManager.createNotificationChannel(channel);
                    }
                }

                notificationManager.notify(mId, mBuilder.build());
```

**Comment by ShridharCodewave** [comment]
Can you please tell me where exactly I should add the above mentioned code?

**Comment by wumke** [comment]
In AlarmReceiver after:
```
                String shortenedDatetime = datetime.replace(":", "").replace("-", "").replace("/", "").replace("\\", "").replace(" ", "").substring(2);
                Integer mId = Integer.parseInt(shortenedDatetime);
```

imports at top of the file if not yet present.

**Comment by ShridharCodewave** [comment]
I did that but getting this error


E:\new scoutnex project\scoutnex_2018\node_modules\react-native-local-notificati
ons\android\src\main\java\com\github\wumke\RNLocalNotifications\AlarmReceiver.ja
va:19: error: cannot find symbol
import android.app.NotificationChannel;
                  ^
  symbol:   class NotificationChannel
  location: package android.app
E:\new scoutnex project\scoutnex_2018\node_modules\react-native-local-notificati
ons\android\src\main\java\com\github\wumke\RNLocalNotifications\AlarmReceiver.ja
va:111: error: package Build does not exist
                if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.O) {
                         ^
E:\new scoutnex project\scoutnex_2018\node_modules\react-native-local-notificati
ons\android\src\main\java\com\github\wumke\RNLocalNotifications\AlarmReceiver.ja
va:111: error: package Build does not exist

**Comment by wumke** [comment]
That indicates that the support:appcompat or buildversion is not high enough (in older versions the NotificationChannel was not known...), do you have the same settings as I mentioned (and minimum needed for android updates in the play store from now on)? 

Also update the local-notifications gradle.build versions to corresponding versions. My versions:

```
apply plugin: 'com.android.library'
android {
    compileSdkVersion 26
    buildToolsVersion "26.0.1"

    defaultConfig {
        minSdkVersion 16
        targetSdkVersion 26
        versionCode 2
        versionName "1.1"
        ndk {
            abiFilters "armeabi-v7a", "x86"
        }
    }
    lintOptions {
       warning 'InvalidPackage'
    }
}

dependencies {
    compile 'com.android.support:appcompat-v7:26.1.0'
    compile 'com.facebook.react:react-native:+'
}
```

**Comment by ShridharCodewave** [comment]
I followed the above instructions but now Iam getting this error
 error: package Build does not exist
         if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.O) {

**Comment by wumke** [comment]
add:
`import android.os.Build;`

Try clearing build cache, rebuilding,...

**Comment by MarkIgnaczakBB** [comment]
@ShridharCodewave 

Did it work for you? I followed the same steps, but it appears to be the same error. 

When app is open, nothing appears

When app is in background, Android says app "crashes", but it doesn't seem to actually close and it still works. Notification doesn't appear though.

**Comment by ShridharCodewave** [comment]
@MarkIgnaczakBB nope, it didn't work for me either

**Comment by MarkIgnaczakBB** [comment]
Here's the crash log:


```
AndroidRuntime: Caused by: java.lang.IllegalArgumentException: Invalid notification (no valid small icon): Notification(pri=0 contentView=[**redacted**] vibrate=[0,1000] sound=null defaults=0x0 flags=0x10 color=0x00000000 vis=PRIVATE)
```

**Comment by MarkIgnaczakBB** [comment]
@ShridharCodewave 
@wumke 

Notifications don't appear when app is open because of this:
https://github.com/wumke/react-native-local-notifications/blob/7f84d5e2a14ae4267b6aaf24605a6482ebb7ae93/android/src/main/java/com/github/wumke/RNLocalNotifications/AlarmReceiver.java#L38

Perhaps this is expected behavior, but some folks probably want notification to appear even when app is already open.

The crash is because this identifier isn't getting anything, so no small icon is being set:
https://github.com/wumke/react-native-local-notifications/blob/7f84d5e2a14ae4267b6aaf24605a6482ebb7ae93/android/src/main/java/com/github/wumke/RNLocalNotifications/AlarmReceiver.java#L51

**Comment by MarkIgnaczakBB** [comment]
So perhaps something like this:

```
final int largeIconResId = res.getIdentifier("ic_launcher", "mipmap", packageName);
final Bitmap largeIconBitmap = BitmapFactory.decodeResource(res, largeIconResId);

NotificationCompat.Builder mBuilder =
        new NotificationCompat.Builder(context)
                .setSmallIcon(largeIconResId)
                .setLargeIcon(largeIconBitmap)
                .setContentTitle(appName)
```

`setSmallIcon()` needs an ID, while `setLargeIcon()` needs a Bitmap.

Right now it looks like this package only supports one image to be read from main project's resource folder:

yourProject/android/app/main/res/drawable

**Comment by DanielClayton** [comment]
It looks like it also supports reading from any directory assuming it exists, such as mipmap.

**Comment by wumke** [comment]
@MarkIgnaczakBB : 

Good point about the choice to display the notifications when in foreground, I'll see what I will do with it in next release. (I think on iOS you cannot pop up notifications in notification centre when the app is on foreground, that's probably why I did it the way it is now, I like apps to behave identical on both platforms... Maybe adding toasts in case on foreground as default setting with possibility to override with notification for android might be a good option.)

Custom Icons and sounds is already on my todo list, but to be honest I'm missing time to implement new features and updates at the moment :-(
