### ISSUE TITLE
BUILD FAILED

### ISSUE THREAD

**Issue by LaurensLang** [wumke/react-native-local-notifications#2]
I installed it as described:

```
Check dependencies
Unable to run command 'Libtool libRNLocalNotifications.a' - this target might include its own product.


** BUILD FAILED **

```

**Comment by wumke** [comment]
Does this help: [https://stackoverflow.com/questions/10448589/this-target-might-include-its-own-product](https://stackoverflow.com/questions/10448589/this-target-might-include-its-own-product) ?
