### ISSUE TITLE
Only the sound is played without the registered message being displayed.

### ISSUE THREAD

**Issue by KijungSong** [wumke/react-native-local-notifications#3]
## android
Only the sound is played without the registered message being displayed.

I registered as below.
```javascript
RNLocalNotifications.createNotification (10, 'Some text', '2017-07-03 00:19', 'default');
```

**Comment by wumke** [comment]
Which Android version? 
What is your app state at the time the notification is scheduled? (Active, background or not running at all?)

**Comment by KijungSong** [comment]
Thank you for quick response.
Tell me if you need more information.

### Environment
Node.js v7.10.0
android version: 6.0.1
device : Galaxy Note5

### app state
**Active:** Only the alarm sound is played and there is no change in the screen.
**background:** Only the alarm sound is played and there is no change in the screen.
**not running at all:** Only the alarm sound is played and the screen does not turn on

**Comment by KijungSong** [comment]
I found the cause.
cannot resolve symbol 'NotificationCompat' in AlarmReceiver.java
So I added support-v4.jar. But the problem was not solved.

**Comment by wumke** [comment]
Allright, good job. Did you clean the project and build it again from scratch? That sometimes helps solving this kind of issues with things that should be fixed but do not seem to find their way into compiled code... 
(I did not investigate it further myself, but I guess I tested it already with success on a Motorola device that was upgraded to android 6.0.1, have to double check that though.)
