### ISSUE TITLE
Custom notification design

### ISSUE THREAD

**Issue by guillaumecodet** [wumke/react-native-local-notifications#6]
Hello,
Is it easily possible to have a more custom notification design ? I need some buttons and events in my notification.
I'm not from java, I managed to do it in a pure java project, but can't find where to put my files to make it working with react-native.

Thanks

**Comment by wumke** [comment]
At the moment, no, there are no custom design options... When I find some time to investigate (or someone sends a pull request) I might include some if the behaviour can be made the same on both platforms with gracefull degrading.

Take a look at the java files in this repository, you'll find the code that builds the notification there. Update that code with parts or your code and it should work for android!
